version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
   
    networks:
      - docker.network
    volumes:
      - .:/var/www